server:
  port: 9002

queue:
  debit-transaction: debit-transaction-queue
  transfer-transaction: transfer-transaction-queue
exchange:
  banking: banking-exchange

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  datasource:
    url: jdbc:mysql://localhost:3306/spring-rabbitmq-banking
    username: root
    password: x9Kl_b!tes
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect