server:
  port: 9003

queue:
  credit-transaction: credit-transaction-queue
  transfer-transaction: transfer-transaction-queue
exchange:
  banking: banking-exchange

spring:
  rabbitmq:
    username: admin
    password: admin
    host: rabbitmq
    port: 5672
  datasource:
    url: jdbc:mysql://mysql-docker:3306
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect